In [1]:
import pandas as pd

for name in ["books", "customers", "orders", "reviews"]:
    df = pd.read_csv(f"../data/lake/bronze/{name}.csv")
    print(name, df.shape)   #(rows, columns)
    display(df.head())

books (1000, 8)

,book_id,title,category,price_raw,rating_raw,availability,url,ingested_at
0,its-only-the-himalayas_981,It's Only the Himalayas,Travel,£45.17,Two,In stock,https://books.toscrape.com/catalogue/its-only-...,2026-10-29T02:15:26.430200+00:00
1,full-moon-over-noahs-ark-an-odyssey-to-mount-a...,Full Moon over Noah’s Ark: An Odyssey to Mount...,Travel,£49.43,Four,In stock,https://books.toscrape.com/catalogue/full-moon...,2026-10-29T02:15:26.430200+00:00
2,see-america-a-celebration-of-our-national-park...,See America: A Celebration of Our National Par...,Travel,£48.87,Three,In stock,https://books.toscrape.com/catalogue/see-ameri...,2026-10-29T02:15:26.430200+00:00
3,vagabonding-an-uncommon-guide-to-the-art-of-lo...,Vagabonding: An Uncommon Guide to the Art of L...,Travel,£36.94,Two,In stock,https://books.toscrape.com/catalogue/vagabondi...,2026-10-29T02:15:26.430200+00:00
4,under-the-tuscan-sun_504,Under the Tuscan Sun,Travel,£37.33,Three,In stock,https://books.toscrape.com/catalogue/under-the...,2026-10-29T02:15:26.430200+00:00

customers (515, 7)

,customer_id,full_name,email,phone,mykad,state,signup_date
0,C0051,Tan Wei Ming,NaN,0141708422,960421-14-7098,WP Kuala Lumpur,2024-05-13
1,C0005,Lim Mei Ling,lim.mei.ling98@hotmail.com,016-4037271,010109-04-9629,Melaka,2025-12-09
2,C0202,Tan Wei Ming,tan.wei.ming96@gmail.com,016-8143264,780607-06-8438,Pahang,2025-08-30
3,C0284,Ahmad bin Omar,NaN,019-3049889,830929-04-0831,Melaka,2024-08-09
4,C0493,Kavitha a/p Suresh,kavitha.suresh79@hotmail.com,+60162926056,970227-05-0443,Negeri Sembilan,2025-03-16

orders (3060, 5)

,order_id,customer_id,book_id,quantity,order_date
0,O00001,C0205,city-of-ashes-the-mortal-instruments-2_675,1,2026-07-04
1,O00002,C0296,most-blessed-of-the-patriarchs-thomas-jefferso...,2,2026-03-06
2,O00003,C0223,hamilton-the-revolution_699,1,2026-06-30
3,O00004,C0324,the-hidden-oracle-the-trials-of-apollo-1_752,2,2026-03-04
4,O00005,C0043,the-darkest-corners_399,2,2026-08-10

reviews (1200, 6)

,review_id,customer_id,book_id,stars,review_text,review_date
0,R00001,C0120,deception-point_426,5,Great value for the price.,2026-04-07
1,R00002,C0372,setting-the-world-on-fire-the-brief-astonishin...,5,"Bungkusan kemas, buku dalam keadaan baik.",2026-07-22
2,R00003,C0036,the-three-searches-meaning-and-the-story_649,3,"Well packed, the book was in perfect condition...",2026-01-21
3,R00004,C0484,the-sandman-vol-3-dream-country-the-sandman-vo...,4,Very well written and easy to follow.,2026-06-19
4,R00005,C0324,the-blind-side-evolution-of-a-game_231,4,"Jalan cerita sangat menarik, tak boleh berhent...",2026-07-04